# Generated by Django 4.2.25 on 2026-03-16 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField()),
                ("env_id", models.CharField(max_length=100)),
                ("env_kwargs", models.JSONField(blank=True, default=dict)),
                ("description", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("intermediate", "Intermedio"),
                            ("advanced", "Avanzado"),
                            ("expert", "Experto"),
                            ("doctorate", "Doctorado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("state_space_info", models.TextField(blank=True)),
                ("action_space_info", models.TextField(blank=True)),
                ("requires_discretization", models.BooleanField(default=False)),
                ("discretization_bins", models.IntegerField(default=20)),
                ("default_episodes", models.IntegerField(default=5000)),
                ("reward_threshold", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Technique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("monte_carlo", "Monte Carlo"),
                            ("td", "Temporal Difference"),
                            ("deep", "Deep Learning"),
                        ],
                        max_length=20,
                    ),
                ),
                ("algorithm_key", models.CharField(max_length=50)),
                ("icon", models.CharField(default="cpu", max_length=20)),
                ("order", models.IntegerField(default=0)),
                ("pseudocode", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TrainingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("running", "Ejecutando"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("num_episodes", models.IntegerField(default=5000)),
                ("gamma", models.FloatField(default=0.99)),
                ("alpha", models.FloatField(default=0.1)),
                ("epsilon", models.FloatField(default=1.0)),
                ("epsilon_decay", models.FloatField(default=0.9995)),
                ("epsilon_min", models.FloatField(default=0.01)),
                ("hidden_layers", models.CharField(default="128,128", max_length=100)),
                ("batch_size", models.IntegerField(default=64)),
                ("target_update", models.IntegerField(default=10)),
                ("replay_buffer_size", models.IntegerField(default=10000)),
                ("learning_rate_dqn", models.FloatField(default=0.001)),
                ("rewards_json", models.TextField(default="[]")),
                ("moving_avg_window", models.IntegerField(default=100)),
                ("best_reward", models.FloatField(blank=True, null=True)),
                ("avg_reward_last_100", models.FloatField(blank=True, null=True)),
                ("total_steps", models.IntegerField(blank=True, null=True)),
                ("execution_time", models.FloatField(blank=True, null=True)),
                (
                    "convergence_graph",
                    models.ImageField(blank=True, null=True, upload_to="graphs/"),
                ),
                ("q_table_size", models.IntegerField(blank=True, null=True)),
                ("extra_metrics", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="rl_app.problem",
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="rl_app.technique",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="problem",
            name="techniques",
            field=models.ManyToManyField(
                related_name="problems", to="rl_app.technique"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="problem",
            unique_together={("slug", "env_id")},
        ),
    ]
